name: Release npm

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: üì• Check out the code
        uses: actions/checkout@v3

      - name: üíø Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: üì• Download deps
        uses: bahmutov/npm-install@v1

      - name: üöÄüì¶ Deploy the library to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: üíø Getting the npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: üîî Notify slack success
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ‚úÖ Deploy successful
          SLACK_MESSAGE: Version ${{ steps.package-version.outputs.current-version}} deployed successfully
          MSG_MINIMAL: actions url,commit
          SLACK_USERNAME: snowflakes-ui Bot
          SLACK_ICON_EMOJI: ':snowflake:'
          SLACK_FOOTER: ''

      - name: ‚ùå Notify slack error
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ‚ùå Deploy error
          SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_COLOR: '#ED0000'
          MSG_MINIMAL: actions url,commit
          SLACK_USERNAME: snowflakes-ui Bot
          SLACK_ICON_EMOJI: ':snowflake:'
          SLACK_FOOTER: ''
